[browser]
serverAddress = "0.0.0.0"
serverPort = 8501

[server]
maxUploadSize = 200
enableXsrfProtection = false
enableCORS = false

# [theme]
# primaryColor="#FFFFFF"

[theme]
base="light"
primaryColor="#485de4"

backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F0F2F6"
textColor="#31333F"
font="sans serif"
base="light"
